import{a as f,S as d,i as l}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();const m="11539560-6ff438bd7cc613d70e4d35abc",h="https://pixabay.com/api/";function p(e){const t={key:m,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0},i=`${h}?${new URLSearchParams(t)}`;return f.get(i).then(n=>n.data.hits).catch(n=>{throw console.error("Error fetching data from Pixabay API:",n),n})}function g(e){const t=document.querySelector("#gallery");t.innerHTML="";const i=e.map(y).join("");t.innerHTML=i,L()}function y({largeImageURL:e,webformatURL:t,tags:i,likes:n,views:r,comments:o,downloads:a}){return`  
    <a href="${e}" class="gallery-item">  
      <img src="${t}" alt="${i}" />  
      <div class="image-info">  
        <p><strong>Likes</strong> ${n}</p>  
        <p><strong>Views</strong> ${r}</p>  
        <p><strong>Comments</strong> ${o}</p>  
        <p><strong>Downloads</strong> ${a}</p>  
      </div>  
    </a>`}function L(){new d(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1}).refresh()}const s={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loader:document.querySelector("#loader"),gallery:document.querySelector("#gallery")};function b(){s.loader.classList.remove("hidden")}function c(){s.loader.classList.add("hidden")}function u(e){l.error({title:"Error",message:e,position:"topRight",timeout:2e3})}function S(e){l.info({title:"",message:e,position:"topRight",timeout:3e3})}function w(e){e.preventDefault();const t=s.input.value.trim();if(!t){u("Please enter a search term!");return}P(t),s.input.value=""}function P(e){b(),p(e).then(t=>{c(),v(t)}).catch(t=>{c(),u("Something went wrong! Please try again later."),console.error("Error fetching images:",t)})}function v(e){e.length===0?S("Sorry, there are no images matching your search query. Please try again!"):g(e)}s.form.addEventListener("submit",w);
//# sourceMappingURL=index.js.map
